[build]
  publish = "_site"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"
  autoLaunch = false

# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

#   [plugins.inputs.thresholds]
#     performance = 0.95
#     accessibility = 1
#     best-practices = 1
#     seo = 1
#     pwa = 1

#   [[plugins.inputs.audits]]
#     path = "/"
